In [2]:
import numpy as np

In [13]:
#numpy中的数据必须一致
b=np.array([4,5,'6'])
b

array(['4', '5', '6'], dtype='<U11')

# 如何创建列表

In [2]:
#方法一：使用array来创建数组
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
#方法二：使用np.arange来创建数组（第三个数字2是步伐）
b=np.arange(0,10,0.5)
b

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [20]:
#方法三：使用np.random来创建N行N列的数组，其中数值是0~1的随机数
c=np.random.random((2,2))
c

array([[0.45199063, 0.46073117],
       [0.64314463, 0.30636701]])

In [25]:
#方法四：使用np.random.randint来创建N行N列的数组，其中值的范围可以通过前面两个参数来指定
c=np.random.randint(0,9,size=(4,4))
c

array([[0, 8, 8, 0],
       [7, 8, 0, 3],
       [3, 4, 3, 2],
       [4, 4, 4, 5]])

In [27]:
#方法五：使用特殊函数生成的数组
d=np.zeros((3,3))#3行3列都为0的数组
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
d=np.ones((4,4))#4行4列的都是1的数组
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
e=np.full((2,3),9)#都为指定数字9的2行3列的数组
e

array([[9, 9, 9],
       [9, 9, 9]])

In [36]:
#对称的数列
e=np.eye(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# ndim可以查看数组的维度

In [53]:

a1=np.array([1,2,3])
print(a1.ndim)
a2=np.array([[1,2,3],[4,5,6]])
print(a2.ndim)
a3=np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]]])
print(a3.ndim)

1
2
3


# shape可以查看这个数组是几行几列
shape是一个元组，里面有几个元素代表是几维数组

In [57]:
 *（2，2，3）的意思是：有2部分，每部分有2行，每一行3个元素
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 2, 3)


# 通过reshape可以修改数组的形状，比如原来是（3，4），那么修改后可以变成（2，6），但不能变成（1，4）

In [60]:
#注意：reshape不会改变原来数组的形状
a4=a3.reshape((2,6))
print(a4)
print(a4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


# 扁平化数组，用flatten,不管这个数组有多那么的复杂都转化为1维的

In [62]:
a5=a3.reshape((1,12))
a5=a3.reshape((12,))
a5=a3.flaten()
print(a5)
print(a5.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# # 通过size可以看到数组总共有多少个元素

# 通过itemsize可以看数组中每个元素所占内存的大小

In [64]:
count=a3.size
itemsize=a3.itemsize
print(count)
print(a3.itemsize)

12
4


In [71]:
# 这里是一维的数组操作
#1、进行索引操作（例如：获取数字4）
#2、进行切片操作（例如：获取数字4~5）
#3、使用步长（例如：获得所有的偶数）
#4、使用负数来做索引（例如：获取最后一个值）
b1=np.arange(10)
print(b1[4])
print(b1[4:6])
print(b1[::2])
print(b1[-1])

4
[4 5]
[0 2 4 6 8]
9


In [79]:
#这里是多维数组的操作
#1、如何获取一组多维的数组（例如：获取0~10的随机数，4行6列）
#2、如何获取第0行的数组呢？
#3、如何获取第一行到第二行的数组呢？（连续的行）
#4、如何获取不连续的行呢？(在中括号里再加入一个中括号)
#5、如何获取第几行第几列的数值？（逗号前面的是行，逗号后面的是列；只有一个数就是行）
#6、如何获取不同行不同列的数值？不连续的（【2，3】是指第2行和第三行；【4，5】是指第4列和第5列，整个的意思就是第2行第4列，和第3行第5列的数）
#7、连续的怎么获取呢？
b2=np.random.randint(0,10,size=(4,6))
print(b2)
print(b2[0])
print(b2[1:3])
print(b2[[0,3]])
print(b2[1,1])
print(b2[[2,3],[4,5]])
print(b2[1:3,4:5])

[[1 6 5 7 1 6]
 [9 6 0 9 2 5]
 [8 9 1 7 7 8]
 [3 2 0 2 6 2]]
[1 6 5 7 1 6]
[[9 6 0 9 2 5]
 [8 9 1 7 7 8]]
[[1 6 5 7 1 6]
 [3 2 0 2 6 2]]
6
[7 2]
[[2]
 [7]]


# 布尔索引

In [80]:
c1=np.arange(24).reshape((4,6))
c1


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [83]:
c1[c1<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
#多个条件，“|”是或者的意思；“&”是并且的意思
c1[(c1<5)|(c1>10)]

array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])

# 如何将替换数值

In [87]:
c2=np.random.randint(0,10,size=(3,5))
c2

array([[7, 1, 5, 7, 6],
       [0, 8, 8, 7, 2],
       [2, 8, 7, 2, 1]])

In [88]:
#例如：把第一行全部换成数值0
c2[1]=0
c2

array([[7, 1, 5, 7, 6],
       [0, 0, 0, 0, 0],
       [2, 8, 7, 2, 1]])

In [91]:
#例如：把第一行全部换成1，2，3，4，5
c2[1]=np.array([1,2,3,4,5])
c2

array([[7, 1, 5, 7, 6],
       [1, 2, 3, 4, 5],
       [2, 8, 7, 2, 1]])

In [92]:
#例如：将所有小于3的数改成1
c2[c2<3]=1
c2

array([[7, 1, 5, 7, 6],
       [1, 1, 3, 4, 5],
       [1, 8, 7, 1, 1]])

In [93]:
#例如：将所<5的数改成1，其他的换成0
result=np.where(c2<5,1,0)
result

array([[0, 1, 0, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 0, 0, 1, 1]])

# 数组的广播机制
总结：如果两个数组的从末尾开始算起的维度长度相等或者有一方为1，我们认为是可以广播兼容的。

In [94]:
#数组与数之间的运算（例如：
c3=np.random.randint(0,5,size=(3,5))
c3

array([[2, 2, 4, 3, 4],
       [0, 0, 3, 3, 0],
       [0, 3, 2, 2, 1]])

In [95]:
c3*2
#这里将每一个数都乘以2

array([[4, 4, 8, 6, 8],
       [0, 0, 6, 6, 0],
       [0, 6, 4, 4, 2]])

# CSV文件的操作

In [97]:
#生成随机数
scores=np.random.randint(0,100,size=(20,2))
scores

array([[67,  6],
       [86, 54],
       [75, 56],
       [91, 65],
       [86, 39],
       [11, 28],
       [27,  5],
       [87,  6],
       [58, 70],
       [ 3, 79],
       [13,  4],
       [35, 59],
       [30, 49],
       [25, 98],
       [27, 98],
       [71, 76],
       [75,  5],
       [69, 84],
       [72,  2],
       [61, 91]])

In [98]:
#保存csv文件（savetxt）
np.savetxt("score.csv",scores,delimiter=",",header="英语,数学",fmt="%d",comments=" ",)

In [99]:
#读取csv文件（loadtxt）
b=np.loadtxt("score.csv",dtype=np.int,delimiter=",",skiprows=1)
b

<ipython-input-99-55d26ac339ef>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b=np.loadtxt("score.csv",dtype=np.int,delimiter=",",skiprows=1)


array([[67,  6],
       [86, 54],
       [75, 56],
       [91, 65],
       [86, 39],
       [11, 28],
       [27,  5],
       [87,  6],
       [58, 70],
       [ 3, 79],
       [13,  4],
       [35, 59],
       [30, 49],
       [25, 98],
       [27, 98],
       [71, 76],
       [75,  5],
       [69, 84],
       [72,  2],
       [61, 91]])

# NAN和 inf值的处理
1、首先，NAN不是一个数字，但它是一个浮点型
2、NAN不等于NAN
3、NAN和任何值坐运算都等于NAN

In [ ]:
# 删除所有NAN的数（也可以换个思路，提取所有不是NAN的数）

# random模块

In [115]:
#seed是种子，即生成的随机数每次都相同
#rand()生成0~1之间的随机数
#randn()生成标准正太分布的数
#randint()生成指定范围内的随机数，并且通过size指定维度
np.random.seed(1)
np.random.rand()
np.random.rand(2,3)
np.random.randn(3,3)
date=np.random.randint(0,10,size=(10,))

array([0, 6, 9, 9, 7, 6, 9, 1, 0, 1])

In [119]:
#choice：在一个列表或者数组中，随机进行采样
date=np.arange(5)
date

array([0, 1, 2, 3, 4])

In [122]:
#例子：从date里选取3个数
np.random.choice(date,3)

array([3, 4, 0])

In [126]:
#例子：从0~10里选取3行4列的数组
np.random.choice(10,size=(3,4))

array([[2, 7, 7, 9],
       [7, 3, 0, 8],
       [7, 7, 1, 1]])

In [130]:
#shuffle：将原来数组元素的位置打乱
date1=np.arange(10)
date1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.random.shuffle(date1)
date1

array([9, 0, 7, 3, 4, 5, 2, 1, 8, 6])

# Axis的理解

In [136]:
#Axis=0是指括号最外那一层，Axis=1是指括号里的那一层，简单说就是：Axis=0是指垂直，Axis=1是指水平
d=np.arange(0,4).reshape(2,2)
d

array([[0, 1],
       [2, 3]])

In [140]:
d.sum(axis=0)

array([2, 4])

In [141]:
d.sum(axis=1)

array([1, 5])

In [142]:
#Max:求最大值
x=np.arange(12).reshape(2,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [145]:
x.max()

11

In [150]:
#当Axis=0时，垂直相比较大小
x.max(axis=0)

array([ 6,  7,  8,  9, 10, 11])

In [151]:
#delete:删除
#举例：删除x中第0个
np.delete(x,0,axis=0)

array([[ 6,  7,  8,  9, 10, 11]])

In [155]:
#例子：定义一个2块2行6列的数组
y=np.arange(24).reshape(2,2,6) 
y

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

# Numpy中常见的函数

In [156]:
#一元函数
#uniform：平均分布
e=np.random.uniform(-10,10,size=(3,5))
e

array([[-2.86936553,  5.05576706,  7.62683659, -9.76661613, -0.03781861],
       [-8.52415977,  5.73902949, -8.7186534 , -2.89379275,  8.83673898],
       [-2.40393426,  5.25840147,  5.43189996, -3.97279009,  5.45478294]])

In [157]:
#1、abs：求绝对值
np.abs(e)

array([[2.86936553, 5.05576706, 7.62683659, 9.76661613, 0.03781861],
       [8.52415977, 5.73902949, 8.7186534 , 2.89379275, 8.83673898],
       [2.40393426, 5.25840147, 5.43189996, 3.97279009, 5.45478294]])

In [158]:
#2、sqrt：开根
np.sqrt(e)

<ipython-input-158-7289056186f3>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(e)


array([[       nan, 2.24850329, 2.76167279,        nan,        nan],
       [       nan, 2.39562716,        nan,        nan, 2.9726653 ],
       [       nan, 2.29312047, 2.33064368,        nan, 2.33554767]])

In [159]:
#3、square：求平方
np.square(e)

array([[8.23325854e+00, 2.55607806e+01, 5.81686364e+01, 9.53867906e+01,
        1.43024707e-03],
       [7.26612998e+01, 3.29364595e+01, 7.60149172e+01, 8.37403649e+00,
        7.80879557e+01],
       [5.77889995e+00, 2.76507860e+01, 2.95055372e+01, 1.57830611e+01,
        2.97546569e+01]])

In [ ]:
#4、exp：计算指数e^x
#5、sign：大于0的变成1，等于0的变成0，小于0的变成-1
#6、ceil：朝着正无穷大的方向取整
#7、floor：朝着负无穷大的方向取证
#8、

In [160]:
import pandas 